name: Sync New Folder to Other Repository

on:
  push:
    branches: [main]

jobs:
  sync-directory:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'  # 또는 대상 브랜치
        fetch-depth: 0  # 모든 히스토리를 가져옵니다.

    - name: Find new directory
      run: |
        # 마지막 커밋에서 추가된 모든 파일 및 디렉토리 목록을 가져옵니다.
        ADDED_ITEMS=$(git diff --diff-filter=A --name-only HEAD^ HEAD)
        echo "Added items: $ADDED_ITEMS"
        
        # 추가된 항목들 중 디렉토리만을 찾습니다.
        for ITEM in $ADDED_ITEMS; do
          echo "ITEM: $ITEM"
          FULL_PATH="./${ITEM}"
          echo "FULL_PATH: $FULL_PATH"
          if [[ -d ${FULL_PATH} ]]; then
            # 첫 번째 찾은 디렉토리의 이름을 NEW_DIR_NAME 변수에 할당합니다.
            NEW_DIR_NAME=${ITEM}
            echo "New directory found: ${NEW_DIR_NAME}"
            break  # 첫 번째 찾은 디렉토리만을 사용하고 루프를 종료합니다.
          fi
        done
        
        # 식별된 디렉토리가 없는 경우 스크립트를 종료합니다.
        if [[ -z "${NEW_DIR_NAME}" ]]; then
          echo "No new directory found."
          exit 1
        fi

    - name: Setup Git config
      run: |
        git config --global user.email "ckh0601@cau.ac.kr"
        git config --global user.name "scottXchoo"
    
    - name: Clone Repository B
      run: |
        rm -rf Algorithm-Problem-Solving
        git clone https://github.com/scottXchoo/Algorithm-Problem-Solving.git
        cd Algorithm-Problem-Solving
        # 레포지토리 B에서 L 디렉토리가 존재하는지 확인하고, 없으면 생성
        mkdir -p LeetCode
        
    - name: Copy new directory to Repository B/L
      run: |
        cp -r ${NEW_DIR_NAME} ../Algorithm-Problem-Solving/LeetCode/
        cd ../Algorithm-Problem-Solving
        git add LeetCode/${NEW_DIR_NAME}
        git commit -m "Add new directory ${NEW_DIR_NAME} to LeetCode"
        git push https://YOUR_ACCESS_TOKEN@github.com/scottXchoo/Algorithm-Problem-Solving.git
      env:
        YOUR_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # 또는 PAT을 사용
