name: Sync LeetCode Directory to Algorithm-Problem-Solving Repository

on: [push]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    # - name: List files
    #   run: |
    #     pwd
    #     ls -la
    
    # - name: Copy files
    #   run: |
    #     # 예시: 'LeetCode' 폴더가 레포지토리 루트에 있다고 가정
    #     mkdir -p Algorithm-Problem-Solving/LeetCode/
    #     cp -r LeetCode/* Algorithm-Problem-Solving/LeetCode/
    #     cd Algorithm-Problem-Solving
    #     git add LeetCode/
    #     git commit -m "Sync new LeetCode directory"
    #     git push https://YOUR_ACCESS_TOKEN@github.com/scottXchoo/Algorithm-Problem-Solving.git HEAD:main
    #   env:
    #     YOUR_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

    - name: Copy new LeetCode directory to Algorithm-Problem-Solving Repository
      run: |
        git config --global user.email "ckh0601@cau.ac.kr"
        git config --global user.name "scottXchoo"
        git clone https://github.com/scottXchoo/Algorithm-Problem-Solving.git
        # 여기서 특정 디렉토리를 복사하는 로직을 구현합니다.
        # 예를 들어, "LeetCode" 디렉토리의 변경 사항을 감지하고 복사합니다.
        cp -r scottXchoo/LeetCode/* scottXchoo/Algorithm-Problem-Solving/tree/main/LeetCode
        cd Algorithm-Problem-Solving
        git add LeetCode/
        git commit -m "Sync new LeetCode directory"
        git push https://YOUR_ACCESS_TOKEN@github.com/scottXchoo/Algorithm-Problem-Solving.git HEAD:main
      env:
        YOUR_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
