name: Sync Folder to Algorithm-Problem-Solving Repository

on:
  push:
    branches:
      - main
    paths:
      - 'LeetCode/**'  # LeetCode 디렉토리 안의 모든 변화를 추적합니다.

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: main

    - name: Sync folder
      run: |
        git config --global user.email "ckh0601@cau.ac.kr"
        git config --global user.name "scottXchoo"
        
        # Algorithm-Problem-Solving 레포지토리를 클론합니다.
        git clone https://github.com/scottXchoo/Algorithm-Problem-Solving.git
        
        # LeetCode 디렉토리의 변경된 폴더만 찾습니다.
        CHANGED_DIRS=$(git diff --name-only HEAD^ HEAD | grep '^LeetCode/' | xargs -I {} dirname {} | uniq)
        
        # 변경된 폴더를 Algorithm-Problem-Solving 레포지토리로 복사합니다.
        for DIR in $CHANGED_DIRS; do
          cp -r $DIR Algorithm-Problem-Solving/LeetCode/
        done
        
        # Algorithm-Problem-Solving 레포지토리에 커밋하고 푸시합니다.
        cd Algorithm-Problem-Solving
        git add .
        git commit -m "Update LeetCode folders"
        git push https://YOUR_ACCESS_TOKEN@github.com/scottXchoo/Algorithm-Problem-Solving.git HEAD:main
      env:
        YOUR_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
