name: Sync to Algorithm-Problem-Solving Repository LeetCode Directory

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: 'scottXchoo/LeetCode'
        ref: 'main'

    - name: Setup temporary directory
      run: |
        mkdir temp_dir
        cp -r * temp_dir/
        mv temp_dir/Algorithm-Problem-Solving temp_dir/temp_APS  # 임시로 이름 변경

    - name: Copy files to Algorithm-Problem-Solving Repository LeetCode Directory
      run: |
        git config --global user.email "ckh0601@cau.ac.kr"
        git config --global user.name "scottXchoo"
        git clone https://github.com/scottXchoo/Algorithm-Problem-Solving.git
        cp -r temp_dir/* Algorithm-Problem-Solving/LeetCode/
        cd Algorithm-Problem-Solving/LeetCode/
        git add .
        git commit -m "Sync files from LeetCode Repository"
        git push https://TOKEN@github.com/scottXchoo/Algorithm-Problem-Solving.git HEAD:main
      env:
        TOKEN: ${{ secrets.ACCESS_TOKEN }}
