name: Sync LeetCode Directory to Algorithm-Problem-Solving Repository

on:
  push:
    paths:
      - 'LeetCode/**'  # LeetCode 디렉토리에 변화가 있을 때만 트리거됩니다.

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'

    - name: Copy new LeetCode directory to Algorithm-Problem-Solving Repository
      run: |
        git config --global user.email "your-email@example.com"
        git config --global user.name "your-github-username"
        git clone https://github.com/scottXchoo/Algorithm-Problem-Solving.git
        # 새로 푸시된 디렉토리의 이름을 확인하고 그 이름을 사용하여 복사합니다.
        NEW_DIR=$(git diff --name-only HEAD^ HEAD | grep '^LeetCode/' | xargs -I {} dirname {})
        cp -r $NEW_DIR Algorithm-Problem-Solving/LeetCode/
        cd Algorithm-Problem-Solving
        git add LeetCode/$NEW_DIR
        git commit -m "Sync new LeetCode directory"
        git push https://YOUR_ACCESS_TOKEN@github.com/scottXchoo/Algorithm-Problem-Solving.git HEAD:main
      env:
        YOUR_ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}  # 액세스 토큰
